#!/usr/bin/env bash
# Backup strategy — MongoDB + WhatsApp session + uploads.
# Produces a single timestamped tarball under ./backups. Run from the repo root.
#
#   sudo bash deploy/backup.sh
#   # cron (daily 03:30, keep 14 days):
#   30 3 * * * cd /opt/certification-workflow && bash deploy/backup.sh >> /var/log/cw-backup.log 2>&1
#
# What's backed up & WHY:
#   • MongoDB dump        — all business state (orders, leads, drafts, audit log, users…)
#   • WhatsApp session    — wa_auth volume: avoids re-scanning the QR after a restore
#   • uploads volume      — receipts/layouts/originals saved locally
# Source of truth note: the Declaration sheet + KB live in Google; Mongo is a replica,
# but the dump still captures everything generated by the agents (drafts, audits, leads).
set -euo pipefail
cd "$(dirname "$0")/.."

TS="$(date +%Y%m%d-%H%M%S)"
OUT_DIR="${BACKUP_DIR:-./backups}"
STAGE="$(mktemp -d)"
RETENTION_DAYS="${RETENTION_DAYS:-14}"
mkdir -p "$OUT_DIR"

source .env 2>/dev/null || true
DB="${MONGO_DB:-certification-workflow}"

echo "==> mongodump ($DB)"
docker compose exec -T mongo sh -c \
  "mongodump --username \"$MONGO_ROOT_USERNAME\" --password \"$MONGO_ROOT_PASSWORD\" --authenticationDatabase admin --db \"$DB\" --archive --gzip" \
  > "$STAGE/mongo-$DB.archive.gz"

echo "==> WhatsApp session + uploads volumes"
# Copy named-volume contents via a throwaway helper container.
docker run --rm -v certification-workflow_wa_auth:/v -v "$STAGE":/out alpine \
  sh -c "cd /v && tar czf /out/wa_auth.tgz . 2>/dev/null || true"
docker run --rm -v certification-workflow_uploads:/v -v "$STAGE":/out alpine \
  sh -c "cd /v && tar czf /out/uploads.tgz . 2>/dev/null || true"

cp .env "$STAGE/.env.snapshot" 2>/dev/null || true

ARCHIVE="$OUT_DIR/backup-$TS.tar.gz"
tar czf "$ARCHIVE" -C "$STAGE" .
rm -rf "$STAGE"
echo "==> Wrote $ARCHIVE ($(du -h "$ARCHIVE" | cut -f1))"

echo "==> Pruning backups older than ${RETENTION_DAYS} days"
find "$OUT_DIR" -name 'backup-*.tar.gz' -mtime +"$RETENTION_DAYS" -delete
echo "Done. (Copy $ARCHIVE off-server — e.g. rclone/scp — for real disaster recovery.)"
